name: Check using r-hub containers

on:
  workflow_dispatch:
    inputs:
      inpcont:
        description: 'Check container'
        required: true
        type: string
        default: 'clang-asan'

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/r-hub/containers/ubuntu-release:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build package
        run: R CMD build --no-manual .

      - name: Upload package artifact
        uses: actions/upload-artifact@v6
        with:
          name: pkg
          path: "*.tar.gz"
          retention-days: 1

  check:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/r-hub/containers/${{ github.event.inputs.inpcont }}:latest

    steps:
    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: pkg
        path: /check

    - name: Manipulate CHECK_ARGS
      run: |
        if ! echo "$CHECK_ARGS" | grep -q -- --no-build-vignettes; then
          CHECK_ARGS="$CHECK_ARGS --no-build-vignettes"
        fi
        if ! echo "$CHECK_ARGS" | grep -q -- --no-manual; then
          CHECK_ARGS="$CHECK_ARGS --no-manual"
        fi
        echo "CHECK_ARGS=$CHECK_ARGS" >> $GITHUB_ENV

    - name: Install dependencies and check package
      run: |
        set -e

        checkdir=${1-/check}

        do_check () {
          pkg=${1}
          echo Checking "$pkg"
          cd `dirname $pkg`
          R -q -e "pak::pkg_install('deps::$pkg', dependencies = TRUE)"
          R CMD check $CHECK_ARGS $pkg
          echo a1
          packagename=$(basename "$pkg" | sed "s/_.*$//")
          echo a2
          cd "${packagename}.Rcheck"
          echo a3
          fail=false
          echo a4
          exfile="${packagename}-Ex.Rout"
          echo a5
          pattern='UndefinedBehaviorSanitizer\|AddressSanitizer'
          echo a6

          if [ -f "${exfile}" ] && grep -q "${pattern}" "${exfile}"; then
              fail=true
              echo ----------------------------------------------------------
              echo "${exfile}"
              echo ----------------------------------------------------------
              cat "${exfile}"
              echo ----------------------------------------------------------
          fi

          echo a7

          # List files with .Rout in the 'check' directory and its subdirectories
          out=$(find . -type f -name "*.Rout" -o -name "*.Rout.*")
          echo a8
          echo "$out"
          fail=0

          # Loop through each found file
          for of in $out; do
              # Read the lines of the file
              if grep -q "${pattern}" "$of"; then
                  fail=true
                  break
              fi
          done

          echo a9

          if [ "$fail" = "true" ]; then exit 1; fi
          echo a10
        }

        for pkg in `ls $checkdir/*.tar.gz`; do
            do_check "$pkg"
        done
      continue-on-error: true

    - name: Upload check result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: check-results-${{ github.event.inputs.inpcont }}
        path: /check
